name: TotalFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${project.version}
description: Plugin for the Total Freedom server.
softdepend:
  - BukkitTelnet
  - Essentials
  - CoreProtect
  - LibsDisguises
  - WorldEdit
  - WorldGuard
  - WorldGuardExtraFlags
  - JDA
  - Votifier
authors: [Madgeek1450, Prozza, gamingto12]
api-version: "1.17"